# Generated by Django 5.1.15 on 2026-02-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("contest_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("phase", models.CharField(blank=True, max_length=50, null=True)),
                ("frozen", models.BooleanField(default=False)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("start_time_seconds", models.IntegerField(blank=True, null=True)),
                ("relative_time_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_time_seconds"],
            },
        ),
        migrations.CreateModel(
            name="ParseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("tasks_added", models.IntegerField(default=0)),
                ("tasks_updated", models.IntegerField(default=0)),
                ("contests_added", models.IntegerField(default=0)),
                ("tags_added", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Parse histories",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("rating", models.IntegerField(blank=True, db_index=True, null=True)),
                ("solved_count", models.IntegerField(db_index=True, default=0)),
                ("tags_list", models.JSONField(default=list)),
                ("time_limit", models.IntegerField(blank=True, null=True)),
                ("memory_limit", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="parser.contest",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="tasks", to="parser.tag")),
            ],
            options={
                "ordering": ["-solved_count"],
                "indexes": [
                    models.Index(
                        fields=["rating", "solved_count"], name="parser_task_rating_8767f4_idx"
                    )
                ],
                "unique_together": {("contest", "index")},
            },
        ),
    ]
