# Generated by Django 5.1.15 on 2026-02-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("default_min_rating", models.IntegerField(default=800)),
                ("default_max_rating", models.IntegerField(default=3500)),
                ("preferred_tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255, null=True)),
                ("min_rating", models.IntegerField(blank=True, null=True)),
                ("max_rating", models.IntegerField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("results_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="parser.usersettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
